site_name: "Ancestors\u2019 Eye \u2014 17th Century"
site_description: "Decade-by-decade essays and dossiers (Virginia, New Netherland, Quaker Delaware Valley)"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.prune     # <— hide sibling decades; show only the active one
    - toc.integrate        # <— move page ToC into the left nav (removes right rail)

  palette:
    scheme: default
    
extra_css:
  - assets/extra.css
  
plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "¶"

nav:
  - Home: index.md
  - Decades:
      # 1600–1610 block
      - 1600–1610:
          - Overview: "decades/1600-1610/1600-1610.md"
          - Life & Context: "decades/1600-1610/1600-1610-life.md"
          - Jamestown 1607–1610: "decades/1600-1610/1607-1610-Jamestown.md"
          - Hudson 1609: "decades/1600-1610/1609-Hudson.md"
          - New Country: "decades/1600-1610/1600-1610-NewCountry.md"
          - Old Country: "decades/1600-1610/1600-1610-OldCountry.md"

      # 1610–1620 block
      - 1610–1620:
          - Overview: "decades/1610-1620/1610-1620.md"
          - Life & Context: "decades/1610-1620/1610-1620-life.md"
          - Virginia 1619: "decades/1610-1620/1619-Virginia.md"
          - Fort Nassau 1614–1618: "decades/1610-1620/1614-1618-FortNassau.md"
          - New Country: "decades/1610-1620/1610-1620-NewCountry.md"
          - Old Country: "decades/1610-1620/1610-1620-OldCountry.md"

  - Downloads:       
      # 1610–1620 block
      - 1610–1620:
          - Decade Module Overview: "downloads/decades/1610-1620/1610-1620%20Decade%20Module%20Overview.pdf"
          - Ancestral Lives: "downloads/decades/1610-1620/1610-1620%20Ancestral%20Lives.pdf"
          - New and Old Country Narratives: "downloads/decades/1610-1620/1610-1620%20New%20and%20Old%20Country%20Narratives.pdf"

  - About:
      - Overview: overview.md
      - Methods & Data: methods-data.md
      - Bibliography: bibliography.md












