site_name: "Ancestors\u2019 Eye \u2014 17th Century"
site_description: "Decade-by-decade essays and dossiers (Virginia, New Netherland, Quaker Delaware Valley)"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.prune     # <— hide sibling decades; show only the active one
    - toc.integrate        # <— move page ToC into the left nav (removes right rail)

  palette:
    scheme: default
    
extra_css:
  - assets/extra.css
  
plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "¶"

nav:
  - Home: index.md
  - Decades:
      - 1610–1620:
          - Overview: decades/1610-1620/1610-1620.md
          - Life & Context: decades/1610-1620/1610-1620-life.md
          - Virginia 1619: decades/1610-1630/1619-Virginia.md
          - FortNassau 1614-1618: decades/1610-1620/1614-1618-FortNassau.md
          - New Country: decades/1610-1620/1610-1620-NewCountry.md
          - Old Country: decades/1610-1620/1610-1620-OldCountry.md
          - Downloads: downloads/decades/1610-1620/ReadMe.md
      - 1620–1630:
          - Overview: decades/1620-1630/1620-1630.md
          - Life & Context: decades/1620-1630/1620-1630-life.md
          - Plymouth 1620–1627: decades/1620-1630/1620-Plymouth.md
          - New Amsterdam 1624–1626: decades/1620-1630/1626-NewAmsterdam.md
          - New Country: decades/1620-1630/1620-1630-NewCountry.md
          - Old Country: decades/1620-1630/1620-1630-OldCountry.md
          - Downloads: downloads/decades/1620-1630/ReadMe.md

  - Downloads:
        - downloads/index.md
        - Further viewing: downloads/further-viewing.md

  - About: overview.md




















