site_name: "Ancestors’ Eye — 17th Century"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"
repo_url: "https://github.com/BillWorstell/WorstellWitnessWaybackMachine"
edit_uri: "edit/main/docs/"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

use_directory_urls: true

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md

  - Decades:
      - decades/index.md
      - decades/bibliography.md
      - 1600–1610:
          - ReadMe: decades/1600-1610/ReadMe.md
          - Overview: decades/1600-1610/1600-1610.md
          - Life & Context: decades/1600-1610/1600-1610-life.md
          - Jamestown 1607–1610: decades/1600-1610/1607-1610-Jamestown.md
          - Hudson 1609: decades/1600-1610/1609-Hudson.md
          - New Country: decades/1600-1610/1600-1610-NewCountry.md
          - Old Country: decades/1600-1610/1600-1610-OldCountry.md
          - Downloads: downloads/decades/1600-1610/ReadMe.md
      - 1610–1620:
          - ReadMe: decades/1610-1620/ReadMe.md
          - Overview: decades/1610-1620/1610-1620.md
          - Life & Context: decades/1610-1620/1610-1620-life.md
          - Virginia 1619: decades/1610-1620/1619-Virginia.md
          - Plymouth 1620: decades/1610-1620/1620-Plymouth.md
          - Fort Nassau 1614–1618: decades/1610-1620/1614-1618-FortNassau.md
          - New Country: decades/1610-1620/1610-1620-NewCountry.md
          - Old Country: decades/1610-1620/1610-1620-OldCountry.md
          - Downloads: downloads/decades/1610-1620/ReadMe.md
      - 1620–1630:
          - ReadMe: decades/1620-1630/ReadMe.md
          - Overview: decades/1620-1630/1620-1630.md
          - Life & Context: decades/1620-1630/1620-1630-life.md
          - Plymouth 1620–1627: decades/1620-1630/1620-Plymouth.md
          - New Amsterdam 1624–1626: decades/1620-1630/1626-NewAmsterdam.md
          - New Country: decades/1620-1630/1620-1630-NewCountry.md
          - Old Country: decades/1620-1630/1620-1630-OldCountry.md
          - Downloads: downloads/decades/1620-1630/ReadMe.md
      - 1630–1640:
          - ReadMe: decades/1630-1640/ReadMe.md
          - Overview: decades/1630-1640/1630-1640.md
          - Life & Context: decades/1630-1640/1630-1640-life.md
          - Massachusetts Bay 1630: decades\1630-1640\1630-MassachusettsBay.md
          - Maryland 1634: decades\1630-1640\1634-Maryland.md
          - Pequot War 1636-1637: decades/1630-1640/1636-1637-PequotWar.md
          - New Country: decades/1630-1640/1630-1640-NewCountry.md
          - Old Country: decades/1630-1640/1630-1640-OldCountry.md
          - Downloads: downloads/decades/1630-1640/ReadMe.md

  - Downloads:
      - ReadMe: downloads/ReadMe.md
      - Overview: downloads/index.md
      - 1600–1610 (folder): downloads/decades/1600-1610/index.md
      - 1610–1620 (folder): downloads/decades/1610-1620/index.md
      - 1620–1630 (folder): downloads/decades/1620-1630/index.md
      - 1600–1610 (folder ReadMe): downloads/decades/1600-1610/ReadMe.md
      - 1610–1620 (folder ReadMe): downloads/decades/1610-1620/ReadMe.md
      - 1620–1630 (folder ReadMe): downloads/decades/1620-1630/ReadMe.md
      - Further viewing: downloads/further-viewing.md
      - Templates:
           - ReadMe: downloads\templates\ReadMe.md
           - Folder ReadMe: downloads\templates\Decade_Folder_ReadMe_TEMPLATE.md
           - Overview: downloads\templates\Decade_Module_Overview_TEMPLATE.md
           - Event Essay: downloads\templates\Event_Essay_TEMPLATE.md
           - Life & Context: downloads\templates\Life_and_Context_TEMPLATE.md

  - Families:
      - Powell:
          - Overview: families/powell/index.md
          - 1600–1610: families/powell/1600-1610.md
          - 1610–1620: families/powell/1610-1620.md
          - 1620–1630: families/powell/1620-1630.md
          - 1630–1640: families/powell/1630-1640.md
      - Williams:
          - Overview: families/williams/index.md
          - 1600–1610: families/williams/1600-1610.md
          - 1610–1620: families/williams/1610-1620.md
          - 1620–1630: families/williams/1620-1630.md
          - 1630–1640: families/williams/1630-1640.md
      - Worstell:
          - Overview: families/worstell/index.md
          - 1600–1610: families/worstell/1600-1610.md
          - 1610–1620: families/worstell/1610-1620.md
          - 1620–1630: families/worstell/1620-1630.md
          - 1630–1640: families/worstell/1630-1640.md
      - Various:
          - DircksVolckertszen: families/volckertszen-dircks.md
          - DirksVolkert: families/volkert-dircks.md
          - Worstall: families/worstall.md

  - Places:
      - Norman's Kill: places/normans-kill-bushwick.md
      - Smit's Vly: places/smits-vly.md
      - Amsterdam: places/amsterdam.md
      - Tintern Angidy Wireworks: places/tintern-angidy-wireworks.md
      - Wray Forest of Bowland: places/wray-forest-of-bowland.md      

  - About:
      - Project overview: overview.md
      - Methods & Data: methods-data.md
      - Bibliography: bibliography.md
