site_name: "Ancestors' Eye — 17th Century"
site_description: "Decade-by-decade essays and dossiers (Virginia, New Netherland, Quaker Delaware Valley)"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - toc.follow
  palette:
    scheme: default

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Orientation: overview.md

  - Decades:
      - 1600–1610:
          - Overview: "decades/1600-1610/1600-1610.md"
          - "What life felt like": "decades/1600-1610/1600-1610-life.md"
          - "New Country": "decades/1600-1610/1600-1610-NewCountry.md"
          - "Old Country": "decades/1600-1610/1600-1610-OldCountry.md"
          - Downloads:
              - "1600–1610 (PDF)": "downloads/decades/1600-1610/1600-1610.pdf"
              - "What life felt like (PDF)": "downloads/decades/1600-1610/1600-1610-life.pdf"
              - "New Country (PDF)": "downloads/decades/1600-1610/1600-1610-NewCountry.pdf"
              - "Old Country (PDF)": "downloads/decades/1600-1610/1600-1610-OldCountry.pdf"
              - "Hudson 1609 (PDF)": "downloads/decades/1600-1610/Hudson 1609.pdf"

      # keep the other decade singles as they are today
      - 1640s: "decades/1640s.md"
      - 1650s: "decades/1650s.md"
      - 1660s: "decades/1660s.md"
      - 1670s: "decades/1670s.md"
      - 1680s: "decades/1680s.md"
      - 1690s: "decades/1690s.md"

  - Families:
      - "Volckertsen / Dircks": "families/volckertsen-dircks.md"

  - Places:
      - "Norman’s Kill / Bushwick": "places/normans-kill-bushwick.md"
      - "Smit’s Vly / Manhattan": "places/smits-vly.md"

  - Methods & Data: methods-data.md
  - Bibliography: bibliography.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BillWorstell/WorstellWitnessWaybackMachine


