site_name: "Ancestors’ Eye — 17th Century"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"
repo_url: "https://github.com/BillWorstell/WorstellWitnessWaybackMachine"
edit_uri: "edit/main/docs/"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

use_directory_urls: true

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md

  - Decades:
      - "1600–1610":
          - Overview: decades/1600-1610/1600-1610.md
          - Life & Context: decades/1600-1610/1600-1610-life.md
      - "1610–1620":
          - Overview: decades/1610-1620/1610-1620.md
          - Life & Context: decades/1610-1620/1610-1620-life.md
          - Virginia 1619: decades/1610-1620/1619-Virginia.md
          - Fort Nassau 1614–1618: decades/1610-1620/1614-1618-FortNassau.md
          - New Country: decades/1610-1620/1610-1620-NewCountry.md
          - Old Country: decades/1610-1620/1610-1620-OldCountry.md
      - "1620–1630":
          - Overview: decades/1620-1630/1620-1630.md
          - Life & Context: decades/1620-1630/1620-1630-life.md
          - Plymouth 1620: decades/1620-1630/1620-Plymouth.md
          - New Amsterdam 1626: decades/1620-1630/1626-NewAmsterdam.md
          - New Country: decades/1620-1630/1620-1630-NewCountry.md
          - Old Country: decades/1620-1630/1620-1630-OldCountry.md
      - "1630–1640":
          - Overview: decades/1630-1640/1630-1640.md
          - Life & Context: decades/1630-1640/1630-1640-life.md
          - Massachusetts Bay 1630: decades/1630-1640/1630-MassachusettsBay.md
          - Pequot War 1636–1637: decades/1630-1640/1636-1637-PequotWar.md
          - New Country: decades/1630-1640/1630-1640-NewCountry.md
          - Old Country: decades/1630-1640/1630-1640-OldCountry.md

  - Downloads:
      - Overview: downloads/index.md
      - ReadMe: downloads/ReadMe.md
      - Further viewing: downloads/further-viewing.md
      - "1600–1610 (folder)": downloads/decades/1600-1610/index.md
      - "1610–1620 (folder)": downloads/decades/1610-1620/index.md
      - "1620–1630 (folder)": downloads/decades/1620-1630/index.md
      - "1630–1640 (folder)": downloads/decades/1630-1640/index.md

  - Families:
      - "Addie Arabelle Powell": families/AddieArabellePowell/index.md
      - "Sarah Crew Williams": families/SarahCrewWilliams/index.md
      - "William Albert Worstell": families/WilliamAlbertWorstell/index.md

  - Persons: persons/index.md

  - Places:
      - Norman’s Kill / Bushwick: places/normans-kill-bushwick.md
      - Amsterdam: places/amsterdam.md
      - Tintern Angidy Wireworks: places/tintern-angidy-wireworks.md
      - Wray (Forest of Bowland): places/wray-forest-of-bowland.md

  - About:
      - Project overview: overview.md
      - Methods & Data: methods-data.md
      - Bibliography: bibliography.md
