site_name: "Ancestors\u2019 Eye \u2014 17th Century"
site_description: "Decade-by-decade essays and dossiers (Virginia, New Netherland, Quaker Delaware Valley)"
site_url: "https://billworstell.github.io/WorstellWitnessWaybackMachine/"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.prune     # <— hide sibling decades; show only the active one
    - toc.integrate        # <— move page ToC into the left nav (removes right rail)

  palette:
    scheme: default
    
extra_css:
  - assets/extra.css
  
plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "¶"

nav:
  - Home: index.md
  - Decades:
      - 1600–1610: decades/1600-1610/1600-1610.md
      - 1610–1620: decades/1610-1620/1610-1620.md
  - Downloads: downloads/index.md
  - About: overview.md

  - Downloads:       
      # 1610–1620 block
      - 1610–1620:
          - Decade Module Overview: "downloads/decades/1610-1620/1610-1620%20Decade%20Module%20Overview.pdf"
          - Ancestral Lives: "downloads/decades/1610-1620/1610-1620%20Ancestral%20Lives.pdf"
          - New and Old Country Narratives: "downloads/decades/1610-1620/1610-1620%20New%20and%20Old%20Country%20Narratives.pdf"

  - About:
      - Overview: overview.md
      - Methods & Data: methods-data.md
      - Bibliography: bibliography.md













